nrfconnect/sdk-trusted-firmware-m

CMakeLists.txt

The toolchain args have been replaced by -DCROSS_COMPILE
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

CMakeLists.txt: Remove unused args to TFM build

---

CMakeLists.txt

Mirror of https://github.com/zephyrproject-rtos/trusted-firmware-m/pull/45
In the process, make a few changes:
- Change some names of files created.
- Minimize the number of files created.
- Use hex files instead of bin files. This is so we don't need to know
the offset when creating hex files from bin files.
Also add signing for MCUBOOT_IMAGE_NUMBER=1 based on the code from the
v2m_musca_b1 board, though, this board does not build with =1 now
because of (I assume) some flash aliasing which places the S and NS
images 0x10000000 apart, where the manual algorithm places them next to
each other. It builds with =2, though.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

[nrf fromlist] CMakeLists.txt: Add signing code consolidated from zephyr boards

---

trusted-firmware-m/bl2/CMakeLists.txt
trusted-firmware-m/config/config_default.cmake
trusted-firmware-m/interface/include/psa/crypto_extra.h
trusted-firmware-m/interface/include/psa/crypto_types.h
trusted-firmware-m/interface/include/psa/crypto_values.h

-Changing from static definition to configurable CMake variable
called MCUBOOT_MBEDCRYPTO_CONFIG_PATH
Signed-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

[nrf temphack]: Adding configurable BL2 config

---

trusted-firmware-m/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_default.h
trusted-firmware-m/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_large.h
trusted-firmware-m/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_medium.h
trusted-firmware-m/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_small.h

-This enables Chacha20, Poly1305 and ChachaPoly configuration options
by default
Manifest pr: [pull/4716](https://github.com/nrfconnect/sdk-nrf/pull/4716)
Upstream TF-M patch: [10191](https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/10191)

[nrf fromlist] Enable ChachaPoly in the default configuration

---

trusted-firmware-m/platform/ext/target/nordic_nrf/common/core/gcc/nordic_nrf_s.ld

This is needed to create minimal builds.
Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>
Upstream patch: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/10218

[nrf fromlist] align within 32kB with minimal config

---

trusted-firmware-m/secure_fw/partitions/protected_storage/crypto/ps_crypto_interface.c
trusted-firmware-m/secure_fw/partitions/protected_storage/crypto/ps_crypto_interface.h
trusted-firmware-m/secure_fw/partitions/protected_storage/ps_encrypted_object.c
trusted-firmware-m/secure_fw/partitions/protected_storage/ps_object_system.c
trusted-firmware-m/secure_fw/partitions/protected_storage/ps_object_table.c
trusted-firmware-m/secure_fw/partitions/protected_storage/ps_utils.c
trusted-firmware-m/secure_fw/partitions/protected_storage/ps_utils.h

-Adds non static key labels for the key derivation
-Client id is used as the label
-The ps_table still has a static label
Upstream PR: [pull/10198](https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/10198)
Ref: NCSDK-9028

[nrf_fromlist] protected_storage: Enable non static key labels

---

trusted-firmware-m/config/config_default.cmake
trusted-firmware-m/secure_fw/partitions/crypto/CMakeLists.txt
trusted-firmware-m/secure_fw/partitions/crypto/crypto_key_derivation.c
trusted-firmware-m/secure_fw/partitions/crypto/crypto_rng.c
trusted-firmware-m/secure_fw/partitions/crypto/tfm_crypto_secure_api.c

Allow users to enable RNG without enabling key derivation.
Ref: NCSDK-100031
Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

[nrf fromlist] partitions: crypto: introduce option to disable RNG ... 

---

platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/CMakeLists.txt
platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/include/tfm_ioctl_api.h
platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/include/tfm_read_ranges.h
platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/src/tfm_platform_system.c
platform/ext/target/lairdconnectivity/common/core/CMakeLists.txt

..service
Add lairdconnectivity platform services for GPIO and read as core
platform services.
The services are added in a way that makes it possible for out-of-tree
boards to include these core services while still being able to add
their own.
Change-Id: If3163c4810f6578ccf76e80f5a8f3b97a95dc591
(cherry picked from commit f1cf48f8f96308c04ed41b208ee68e6d2855099b)
(cherry picked from commit 5d32c3e64b3d589548e881eeeeb37d84944c90af)

[nrf fromtree] platform: lairdconnectivity: Add platform GPIO and read..

---

bl2/CMakeLists.txt
platform/CMakeLists.txt
secure_fw/partitions/crypto/CMakeLists.txt
secure_fw/partitions/crypto/tfm_crypto.yaml

Remove TF-M linking against MbedTLS project TLS and X509 libraries.
Allow Crypto partition to be include without ITS partition.

TF-M: Minimal build dependency fixes

---

platform/ext/target/lairdconnectivity/common/bl5340/CMakeLists.txt
platform/ext/target/nordic_nrf/common/nrf5340/CMakeLists.txt
platform/ext/target/nordic_nrf/common/nrf9160/CMakeLists.txt
platform/ext/target/nordic_nrf/common/nrf9160/target_cfg.c

-As described in the Product Specification the FPU is not
affected by any security configuration and the the
Present field in the PERM SPU register is not enabled.
-Add missing NRF_SKIP_FICR_NS_COPY_TO_RAM to BL2 build and nrf9160
platform.
Upstream PR:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/13999
Upstream PR:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/13994
Change-Id: I76517363d548c9a5f4b3461aee2fdce801996842
Change-Id: Ib99dbc36b45bc4659cb8eebc8b9143b10fe32da4

[nrf fromlist] platform: Don't  configure FPU for nrf9160

---

platform/ext/target/nordic_nrf/common/core/CMakeLists.txt
platform/ext/target/nordic_nrf/common/core/config.cmake
platform/ext/target/nordic_nrf/common/core/hw_init.c

Reset nRF peripherals during boot.
This is required when using an MCUBoot version without CONFIG_MCUBOOT_NRF_CLEANUP_PERIPHERAL enabled.
This is by default enabled starting from NCS 1.4.

TF-M: Reset nRF peripherals during boot

---

secure_fw/partitions/crypto/tfm_crypto.yaml
tools/templates/partition_intermedia.template

Add configurable stack size for the TF-M crypto partition.
This is a temporary method of adding this configuration since the
upstream TF-M implementation for this feature could not be backported
in a clean way.
Should be replaced by the upstream feature in future TF-M upmerge:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/16125

[nrf noup] Add configurable stack size for crypto partition.

---

interface/src/tfm_crypto_ipc_api.c
platform/ext/target/lairdconnectivity/common/core/CMakeLists.txt
platform/ext/target/nordic_nrf/common/core/CMakeLists.txt

Add the non-secure API IOCTL functions for the nordic platform to the
set of source files exported in the install folder.
In the case where this is built by an external build system instead of
the platform_ns library then this source file needs to be included in
the non-secure application and its build system.

[nrf fromtree] tfm: Export IOCTL non-secure API source file to install

---

platform/ext/target/nordic_nrf/common/nrf9160/CMakeLists.txt

Fixed CMakeLists.txt bug where we added NRF_NS_SECONDARY to nrf53, but
forgot to add it to nrf91. This broke NRF_NS_SECONDARY for 91.
Fix from Joan Minana.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

[nrf toup] platform: nordic_nrf: Fixed NRF_NS_SECONDARY bug

---

secure_fw/partitions/crypto/crypto_key_derivation.c

fixup! [nrf toup] SPM: Updating abort functionality in TF-M secure services
Fix the input validation and abort handling for the crypto secure
functions tfm_crypto_key_derivation_set_capacity and
tfm_crypto_key_derivation_output_bytes.
This was causing problems in the following PSA arch test cases:
Test 220
Test 221
Test 222
Test 223
NCSDK-16364
NCSDK-16487

[nrf toup] SPM: Fix input validation and abort handling for crypto

---

platform/ext/target/lairdconnectivity/common/bl5340/target_cfg.c
platform/ext/target/lairdconnectivity/common/core/plat_test.c
platform/ext/target/nordic_nrf/common/core/plat_test.c
platform/ext/target/nordic_nrf/common/core/services/include/tfm_ioctl_core_api.h
platform/ext/target/nordic_nrf/common/core/services/src/tfm_platform_hal_ioctl.c
platform/ext/target/nordic_nrf/common/nrf5340/target_cfg.c

This commit replaces API that became deprecated with the release
of nrfx2.9 - see CHANGELOG in NordicSemiconductor:nrfx repository
https://github.com/NordicSemiconductor/nrfx/blob/v2.9.0/CHANGELOG.md
Signed-off-by: Adam Wojasinski <adam.wojasinski@nordicsemi.no>

[nrf toup] platform: nordic_nrf: Replace deprecated API with new one

---

platform/ext/target/nordic_nrf/common/core/gcc/nordic_nrf_s.ld
platform/ext/target/nordic_nrf/common/nrf5340/config.cmake
platform/ext/target/nordic_nrf/common/nrf9160/config.cmake
secure_fw/partitions/crypto/crypto_aead.c

Add the psa_call_pack and psa_interface_svc to
the unprivilleged part of the image. When
isolation level >1 is used the PSA application
RoT partitions (such as PS) run in unprivilleged
mode and they need to be able to access these
functions when accessing any other RoT services
(such as ITS).
Upstream PR:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/15740
Change-Id: Id82e8fadd1822930162b7bb8b1f434891c5f20d2

[nrf fromtree] Bug fixes for isolation level 2

---

CMakeLists.txt

Replace the path of tf-m-tests repo with the literal
"TFM_TEST_REPO_PATH" in C preprocessor macro expansions to prevent
host file path information from leaking into __FILE__ macros and
breaking reproducible builds.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

[nrf toup] Test: Build: Don't put host filepaths into firmware

---

secure_fw/CMakeLists.txt
tools/templates/veneer_function_names.template
tools/tfm_generated_file_list.yaml

patches submitted to upstream for review, and revisions to them:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/16703
The linker removes the debug section of the object files, that are
invoked indirectly via the generated veneer functions. Why this
happens, is not fully clear. This commit adds a workaround that
tells the linker to include the functions that are called via a
veneer function. This is done by generating the linker option
-Wl,--undefined=function_name for all veneer functions and writing
them into a file that then later gets added as linker option to
the tfm_s target.
As mentioned it is a workaround, as the root cause is not fully
clear and might be a bug in the ld linker.
Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

[nrf noup] Added workaround for missing Debug symbols in tfm_s image

---

secure_fw/spm/cmsis_func/spm_func.c

Fixes build warning seen with zephyr 0.15.0 toolchain.
Signed-off-by: Vidar Lillebø <vidar.lillebo@nordicsemi.no>

Fix build warnings

---

secure_fw/spm/cmsis_func/spm_func.c

fixup! [nrf noup] Fix build warnings
Fix the stack seal writing of the stack seal value to an invalid pointer. This caused a hardfault during init of the code and library model never boots.

[nrf noup] secure_fw: Fix stack seal writing using invalid pointer

---

platform/ext/target/nordic_nrf/common/core/native_drivers/spu.c
platform/ext/target/nordic_nrf/common/core/native_drivers/spu.h
platform/ext/target/nordic_nrf/common/nrf5340/target_cfg.c
platform/ext/target/nordic_nrf/common/nrf9160/target_cfg.c

With a bootloader enabled some regions are locked and cannot be reset by TF-M. This commit checks whether the region is locked before resetting them.

Do not attempt to reset locked regions

---

platform/ext/target/nordic_nrf/common/nrf5340/partition/region_defs.h
platform/ext/target/nordic_nrf/common/nrf9160/partition/region_defs.h

fixup! [nrf noup] Add configurable stack size for crypto partition.
Add missing definition of CRYPTO_STACK_SIZE when NCS TF-M is built in vanilla TF-M configuration.
This is useful in testing scenarios when sending patches upstream.

[nrf noup] Fix configurable stack size in non-NCS build

---

platform/ext/target/lairdconnectivity/common/core/plat_test.c
platform/ext/target/nordic_nrf/common/core/plat_test.c

This commit replaces deprecated nrf_timer_frequency_t enum with new numerical value.
Signed-off-by: Adam Wojasinski <adam.wojasinski@nordicsemi.no>

[nrf toup] nrf: Replace deprecated enum for timer prescaler

---

config/config_base.cmake
platform/ext/target/nordic_nrf/common/core/CMakeLists.txt
platform/ext/target/nordic_nrf/common/core/tfm_hal_its_encryption.c
platform/ext/target/nordic_nrf/common/core/tfm_hal_its_encryption.h
platform/ext/target/nordic_nrf/common/nrf5340/CMakeLists.txt
platform/ext/target/nordic_nrf/common/nrf5340/config.cmake
platform/ext/target/nordic_nrf/common/nrf9160/CMakeLists.txt
platform/ext/target/nordic_nrf/common/nrf9160/config.cmake
platform/include/tfm_hal_its.h
secure_fw/partitions/internal_trusted_storage/CMakeLists.txt
secure_fw/partitions/internal_trusted_storage/flash_fs/its_flash_fs.c
secure_fw/partitions/internal_trusted_storage/flash_fs/its_flash_fs.h
secure_fw/partitions/internal_trusted_storage/flash_fs/its_flash_fs_mblock.h
secure_fw/partitions/internal_trusted_storage/its_crypto_interface.c
secure_fw/partitions/internal_trusted_storage/its_crypto_interface.h
secure_fw/partitions/internal_trusted_storage/its_utils.h
secure_fw/partitions/internal_trusted_storage/tfm_internal_trusted_storage.c
secure_fw/partitions/internal_trusted_storage/tfm_internal_trusted_storage.h
secure_fw/partitions/internal_trusted_storage/tfm_its_req_mngr.c

This adds the support for EITS again, which had to be reverted for the update to TF-M 1.7
As the upstream PR didn't get merged yet.
-Adds encryption and authentication support for ITS files 
-Encryption is optional and is enabled using a CMake variable
-The encryption implementation is platform dependent, the signatures of the functions are provided in this change
Ref: NCSDK-19574
Change-Id: Iea6ed79907f046a79ff7ff44ea2c7285ee14ddab

[nrf toup]: ITS: Add support for encrypted ITS

---

secure_fw/partitions/internal_trusted_storage/tfm_its_req_mngr.c

fixup! [nrf toup]: ITS: Add support for encrypted ITS
Fix build warning when Encrypted ITS is not enabled: warning: 'buffer_size_check' defined but not used [-Wunused-function].

[nrf toup] ITS: Fix build warning when Encrypted ITS is not enabled

---

secure_fw/partitions/crypto/crypto_init.c

This reverts commit 35403fc74543fa0c51865b562b22a9759a6027de.

Revert "[nrf noup] secure_fw: Remove mbedtls_platform_set_printf call"

---

interface/include/psa/crypto.h
interface/include/psa/crypto_sizes.h

Fix use of PSA config in PSA crypto interface headers.
This PR addreses the issue that PSA_HASH_MAX_SIZE will default to 32 instead of 64 when PSA configurations are not available to the PSA headers.
This PR also aligns with upstream way to include PSA configuration headers, however NCS does not define the right configurations yet to make this optimal configuration.

crypto: Fix use of PSA config in PSA crypto interface headers

---

secure_fw/partitions/internal_trusted_storage/config_its.h

Fix compilation error in the Internal Trusted Storage partition when disabling the Protected Storage partition.
This is a noup patch because the header files no longer exists in upstream.

[nrf noup] secure_fw: Fix compile error with ITS enabled PS disabled

---

platform/ext/target/nordic_nrf/common/core/startup.h
platform/ext/target/nordic_nrf/common/nrf5340/gcc/startup_nrf5340.c
platform/ext/target/nordic_nrf/common/nrf91/gcc/startup_nrf91.c

Fix a bug in the startup file where the ifdef was incorrectly negated.
Also add declarations for when the default irq handler is not used.

startup_file_improvements: [nrf noup] platform: nordic_nrf: Bugfix in startup file

---

platform/ext/target/nordic_nrf/common/nrf91/nrfx_config_nrf91.h

The MDK for nRF9120 used in the nRF9161 target doesn't define the Secure FPU as it doesn't exist, but for other platforms like the 9160 it has a dummy define, with an UNUSED field in the type.
The long plan is to get this fixed in the MDK but until then, to make the nrfxlib 3.1.0 update possible this tempfix is applied.
Ref: NCSDK-23046
Change-Id: I44042ee9aada99c59a5930440306bb6c40ae4880

[nrf noup] platform: nrf_nordic: Add temp fix for for secure FPU on 9161

---

platform/ext/target/nordic_nrf/common/core/target_cfg.c

This fixes an erroneous attempt to configure the FPU peripheral in NRF91 series. The FPU is not configurable in NRF91 series and it is always non-secure. This caused a failed assertion in the initialzation since the FPU present field is not set for the SPU configuration.
This change configures the FPU only in NRF53 series devices which have a configurable FPU.
Ref: NCSDK-23619
Change-Id: Ia00e0e620ab51850e6ee8b382e5d03a245b6db0c

[nrf fromlist] platform: nordic_nrf: Fix assert in initialization

---

platform/ext/target/nordic_nrf/common/core/common/nrfx_glue.h

Updated nrfx_uarte driver requires missing atomic macros:
- nrfx_atomic_t
- NRFX_ATOMIC_FETCH_*
Signed-off-by: Nikodem Kastelik <nikodem.kastelik@nordicsemi.no>
(cherry picked from commit 33c0f47bcb19721a5c33e6fe1eee9225d00bb5bc)

[nrf fromtree] platform: nordic_nrf: add builtin atomic macros to glue

---

config/profile/config_profile_medium.h
config/profile/config_profile_medium_arotless.h
config/profile/config_profile_small.h
platform/ext/target/nordic_nrf/common/core/target_cfg.c
secure_fw/partitions/crypto/crypto_check_config.h

1.
Fix regression since target_cfg.c was refactored to a common file
for nrf91 and nrf53.
The I2S and PDM peripheral are not configured as non-secure peripherals.
2.
Disable the cipher crypto module in small, medium and mediuam-arotless
profile. There is no algorithm for this module enabled in the mbedcrypto
configuration header for these profiles.
Add missing PSA defined algorithms and keys checks.
The checks only covered supported algorithms in mbedtls.
However mbedtls supports accelerated PSA crypto support through the
psa crypto driver wrappers, which can support additional algorithms
and key types.

Fix psa want missing

---

secure_fw/partitions/crypto/CMakeLists.txt

TF-M checks if P256M is available during build time using MBEDCRYPTO_PATH which is set to the TF-M repo to use custom mbed TLS cmake configurations, but this means the script can not be found. But as mbed TLS software crypto is not used anyway we can hardcode P256M to be disabled.
Change-Id: I94fde1f41e3493e840823cae284256176a364863

[nrf noup] Remove check for P256M

---

tools/CMakeLists.txt

In the TF-M build scripts we run the manifest tool twice, first from CMake and then from ninja.
It is bad practice to configure CMake projects like this. Instead, if configuration from CMake is necessary, one should configure from CMake only, and then re-run CMake when necessary, not just the command.
This organization has been causing problems for our users as they have been required to rebuild TF-M twice.
This is due to this scenario playing out:
CMake generates config_impl.cmake by invoking the manifest tool at Configure time.
CMake generates build.ninja.
Ninja generates config_impl.cmake by invoking the manifest tool at build time.
When the user then invokes ninja a second time config_impl.cmake will be newer than build.ninja. But CMake is supposed to be includ'ing config_impl.cmake, …

cmake: tools: Dont add a custom command for running the manifest

---

interface/include/psa/crypto_extra.h
interface/include/psa/crypto_sizes.h
interface/include/psa/crypto_struct.h
interface/include/psa/crypto_types.h
interface/include/psa/crypto_values.h
interface/include/tfm_crypto_defs.h
interface/src/tfm_crypto_api.c
secure_fw/partitions/crypto/CMakeLists.txt
secure_fw/partitions/crypto/Kconfig.comp
secure_fw/partitions/crypto/crypto_check_config.h
secure_fw/partitions/crypto/crypto_init.c
secure_fw/partitions/crypto/crypto_pake.c
secure_fw/partitions/crypto/crypto_spe.h
secure_fw/partitions/crypto/tfm_crypto_api.h

This is noup commit as upstream TF-M relies on the mbed TLS PSA Core that does not support the PAKE API's according to 1.2 at the moment. Once this exists then this can be up streamed, or removed if TF-M adds it themself.
Added PAKE API support according to the PSA crypto spec 1.2
Ref: NCSDK-22416

[nrf noup] crypto: Add PAKE support

---

platform/ext/target/nordic_nrf/common/core/target_cfg.c

This reverts commit a22fef345c7d2287636dab3b750348cc88e8e79f.
The commit is no longer needed after updating nrfx to version 3.4.0.

Revert "[nrf noup] Add missing SPU funcs in target_cfg.c"

---

interface/include/tfm_crypto_defs.h
interface/src/tfm_crypto_api.c
secure_fw/partitions/crypto/crypto_key_derivation.c
secure_fw/partitions/crypto/crypto_spe.h

Cherry pick from upstream TF-M to support psa_key_derivation_input_integer needed for pbkdf2.

Crypto: Add missing key derivation APIs in the interface

---

config/config_base.cmake
interface/include/psa/crypto_values.h
secure_fw/partitions/crypto/crypto_library.c
secure_fw/partitions/protected_storage/crypto/ps_crypto_interface.c

Allows custom key-loader to be used for the PSA core and allows configuring CMAC KDF usage for PS.

[nrf noup] Support CMAC KDF and custom builtin solution

---

platform/ext/target/nordic_nrf/common/core/target_cfg.c

fixup! [nrf noup] platform: nordic_nrf: Add support for 54l
Configure the XL1 and XL2 to be controlled by GPIO or peripheral. This is need to ust the ow-frequency crystal oscillator (LFXO). This can only been done from secure therefore do it in TF-M
Ref: NCSDK-26595

[noup] platform: nordic_nrf: Add LFXO support for 54L

---

platform/ext/target/nordic_nrf/common/core/target_cfg.c

For Secure only builds on 53 there exists the Kconfig CONFIG_SOC_ENABLE_LFXO to define if the XL1 and XL2 pin should be configured to used for the LFXO oscillator. TF-M should have the same behavior, to enable the possibility to use these pins for something else
noup as we don't have the NCS Kconfigs available in upstream TF-M, the change to pull them in was done in the noup commit: 1a178885e758b2a40a60a0dd419a29ed94236965
Ref: NCSDK-20678

[noup] platform: nordic_nrf: Configure XL1/2 pin based on Kconfig

---

platform/ext/target/nordic_nrf/common/core/tfm_hal_its_encryption_cracen.c

!fixup [nrf noup] platform: nordic_nrf: Add support for 54l
Due to dependencies problems between the ITS and crypto partitions refactoring the ITS encryption interface to use the HUK library and the cracen driver directly.

[nrf noup] platform: nordic_nrf: 54L Use HUK library for EITS

---

cmake/version.cmake

Version check depends on upstream's tagging scheme which differs from NCS's

[nrf noup] Fix version warning

---

platform/ext/target/lairdconnectivity/bl5340_dvk_cpuapp/services/include/tfm_platform_user_memory_ranges.h
platform/ext/target/nordic_nrf/common/core/services/include/tfm_ioctl_core_api.h
platform/ext/target/nordic_nrf/common/core/services/include/tfm_platform_hal_ioctl.h
platform/ext/target/nordic_nrf/common/core/services/src/tfm_ioctl_core_ns_api.c
platform/ext/target/nordic_nrf/common/core/services/src/tfm_platform_hal_ioctl.c
platform/ext/target/nordic_nrf/nrf5340dk_nrf5340_cpuapp/services/include/tfm_platform_user_memory_ranges.h
platform/ext/target/nordic_nrf/nrf9160dk_nrf9160/services/include/tfm_platform_user_memory_ranges.h
platform/ext/target/nordic_nrf/nrf9161dk_nrf9161/services/include/tfm_platform_user_memory_ranges.h

There are some hardware registers in Nordic platforms which are mapped as secure only. In order to allow the non-secure application to control these registers I added here a secure service which allows 32-bit writes to secure mapped memory. The writes are only allowed on  addresses and masks defined in a header list. It is also possible to provide an allowed_values list in order to further limit the accepted values.
Renamed:  tfm_read_ranges.h -> tfm_platform_user_memory_ranges.h since now it can be used for both reads and writes.
The list in the current platforms is empty and might be populated later.

[nrf fromtree] platform: nordic: Add platform memory write service

---

platform/ext/common/gcc/tfm_common_s.ld

Add a custom section in the linker script for the CRACEN KMU driver use by nRF54L15. We need a buffer in a static memory location which wil be used by the KMU to perform push operations.
It's a noup since the KMU is not supported fully upstream yet.
Ref: NCSDK-25121

[nrf noup] platform: ext: nordic_nrf: Custom nRF54L15 linker section

---

platform/ext/common/gcc/tfm_common_s.ld

This was missed in a previous commit without this the linker will place the initialization of this global variable which is 0 at the address of S_DATA_START in Flash,now it will be discarded.
Ref. NCSDK-25121

[noup] KMU: Add NOLOAD to linker section for the nRF KMU region

---

platform/ext/target/nordic_nrf/common/core/CMakeLists.txt
platform/ext/target/nordic_nrf/common/core/config.cmake
platform/ext/target/nordic_nrf/common/core/target_cfg.c

NRF_APPROTECT and NRF_SECURE_APPROTECT
to take precedence over other mechanisms when configuring debugging for TF-M.
For nRF53 and nRF91x1 the actual locking of firmware is done elsewhere. This further locks the UICR.
nRF9160 supports only hardware APPROTECT. This will lock the APPROTECT / SECUREAPPROTECT in the next boot, when the above settings are configured.
Change-Id: I5e304be0f8a34c0016488d9ec09929bbcb38481f
Signed-off-by: Markus Lassila <markus.lassila@nordicsemi.no>
(cherry picked from commit 734a51d3b18422ad516e08e7ddc107e921d64180)

[nrf fromtree] platform: nordic_nrf: APPROTECT to lock debugging

---

platform/ext/target/nordic_nrf/common/core/faults.c
platform/ext/target/nordic_nrf/common/core/target_cfg.c

fixup! [nrf noup] platform: nordic_nrf: Add support for 54l
Clear the MPC events before you enable the MPC interrupt.

[nrf noup] platform: nordic_nrf: Add support for 54l

---

platform/ext/target/nordic_nrf/common/core/services/src/tfm_platform_hal_ioctl.c

On certain nRF plaforms, like nRF9160, reading UICR registers might need special handling, which is already implemented in nrfx_nvmc_uicr_word_read() so use that, instead on memcpy().
For more information, see nRF9160 Errata 7.
Change-Id: Iea9d0bf4184decd5650b4d4b620fbef0c64a55f6
Signed-off-by: Seppo Takalo <seppo.takalo@nordicsemi.no>
(cherry picked from commit ca03e40149cc7a376c7d8f5511df60431b832929)

[nrf fromtree] platform: nordic: Allow reading UICR registers

---

platform/ext/target/nordic_nrf/common/core/services/src/tfm_platform_hal_ioctl.c

fixup! [nrf noup] platform: nordic_nrf: Add support for 54l
The latest nrfx removes the define NRF_GPIO_PIN_SEL_TND for the nRF54L15 indirectly since it removes the define: GPIO_PIN_CNF_MCUSEL_TND and the GPIO_PIN_CNF_CTRLSEL_TND is also not defined.

[nrf noup] platform: nordic_nrf: Remove unused define for nRF54L15

---

platform/ext/target/nordic_nrf/common/core/cmsis_drivers/Driver_USART.c
platform/ext/target/nordic_nrf/common/core/target_cfg.c

Fix some configuration issues with the secure UART which caused build failures or TF-M panics. In essence what these changes do is that:
1) Make sure that if no secure UART is being enabled we don't include any UART configuration code. 
2) Make sure that the configuration of the UART includes all the available UART ports.

UART fixes for nRF54l

---

platform/ext/target/nordic_nrf/common/core/target_cfg.c

Do not attempt to lock the UICR.APPROTECT or UICR.SECUREAPPROTECT for nRF54L15. These registers do not exist.
TF-M provisioning with nRF54L15 will still result in compilation failure. As it should at this point.

[nrf noup] platform: nordic_nrf: nRF54L15 does not have UICR

---

secure_fw/partitions/protected_storage/ps_object_system.c

Add missing capacity in tfm_ps_get_info calls.
Change-Id: I37432d204ee87971915471dce9b3a2ebcce057e2
Signed-off-by: Markus Lassila <markus.lassila@nordicsemi.no>
(cherry picked from commit fafe163c21736bf454568e28510da8977215f287)

[nrf fromtree] Protected Storage: Add capacity in tfm_ps_get_info calls.

---

platform/ext/target/nordic_nrf/common/core/target_cfg.c

Setting OWNERID is not available on all devices.
This PR is needed for nrfx 3.10 integration in NCS

[nrf fromtree] platform: nrf: ifdef MPC OWNERID configuration

---

platform/ext/target/nordic_nrf/common/core/hw_init.c

Some devices do not have RTC peripheral.
Upstream PR #: 35302

[nrf fromtree] platform: nrf: ifdef nrf_rtc.h inclusion

---

secure_fw/partitions/protected_storage/ps_object_table.c

NVC_2 and NVC_3 should not be aligned to NVC_1 unless the object table has been successfully stored to persistent memory.
When storing an object to PS, the object is stored first and the object table is updated afterwards. If there is not enough memory for the object table, NVC_1 is increased, but NVC_2 and NVC_3 are not. Reset the device. Object table is validated with NVC_3. Now, if NVC_2 and NVC_3 are brought to be on par with NVC_1 and the object table is not saved and the device is reset again, the object table can no longer be validated. New object tables are created, which loses all the data stored to PS.
Change-Id: I9eb680d507d5aac251bede586b6c39c751815dcb
Signed-off-by: Markus Lassila <markus.lassila@nordicsemi.no>
(cherry picked from commit …

Protected Storage: Do not align NV counters in init

---

cmake/version.cmake

Get rid of the CMake warning which happens when `TFM_VERSION_MANUAL` mismatches `TFM_VERSION_FULL`.
The latter is obtained with Git tags, which cannot be relied on in NCS.

(3.0) [nrf noup] Remove version mismatch CMake warning

---

cmake/version.cmake

Get rid of the CMake warning which happens when `TFM_VERSION_MANUAL` mismatches `TFM_VERSION_FULL`.
The latter is obtained with Git tags, which cannot be relied on in NCS.

(2.9) [nrf noup] Remove version mismatch CMake warning

---

cmake/version.cmake
platform/ext/common/template/flash_otp_nv_counters_backend.h

nrf-squash! [nrf noup] build: fix TF-M version
Fixes an issue where the TFM_VERSION was not set because the return() statement exited early.
This removes all the logic from the unused logic from the version.cmake since it is irrelevant.

[nrf noup] version: Fix TFM_VERSION being undefined
